version: '3'

volumes:
  mysql_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: great_url_shortener_local_django
    depends_on:
      - mysql
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mysql
    ports:
      - "8000:8000"
      - "3000:3000"
    command: /start

  mysql:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.envs/.local/.mysql
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:5.0

  vue:
    build:
      context: .
      dockerfile: ./compose/local/vue/Dockerfile
    volumes:
      - ./vue:/app
    depends_on:
      - django
    ports:
      - 5000:8080
