#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



# N.B. If only .env files supported variable expansion...
export CELERY_BROKER_URL="${REDIS_URL}"

mysql_ready() {
python << END
import sys

from MySQLdb.connections import Connection

try:
    db = Connection(
        host="mysql",
        user="${MYSQL_USER}",
        password="${MYSQL_PASSWORD}",
        database="${MYSQL_DATABASE}",
        port=3306,
    )
except:
    sys.exit(-1)
sys.exit(0)

END
}
until mysql_ready; do
  >&2 echo 'Waiting for MySQL to become available...'
  sleep 5
done
>&2 echo 'MySQL is available'

exec "$@"
